import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#131313',
        'outline-variant': '#3b494c',
        'on-primary-fixed-variant': '#004f58',
        background: '#131313',
        'on-secondary-container': '#0f6d00',
        'secondary-fixed': '#79ff5b',
        'on-background': '#e5e2e1',
        'on-tertiary-fixed': '#251a00',
        'on-secondary-fixed-variant': '#095300',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed': '#022100',
        'inverse-on-surface': '#313030',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-container': '#00626e',
        'inverse-primary': '#006875',
        'primary-fixed': '#9cf0ff',
        surface: '#131313',
        'on-tertiary-fixed-variant': '#594400',
        'primary-container': '#00e5ff',
        'surface-container-high': '#2a2a2a',
        'primary-fixed-dim': '#00daf3',
        'on-tertiary': '#3e2e00',
        'secondary-container': '#2ff801',
        primary: '#c3f5ff',
        'surface-bright': '#393939',
        outline: '#849396',
        'secondary-fixed-dim': '#2ae500',
        'tertiary-fixed': '#ffdf96',
        'surface-container-highest': '#353534',
        'surface-container': '#201f1f',
        'tertiary-fixed-dim': '#f3bf26',
        'on-primary': '#00363d',
        tertiary: '#ffeac0',
        'inverse-surface': '#e5e2e1',
        'on-primary-fixed': '#001f24',
        secondary: '#d7ffc5',
        'on-tertiary-container': '#6f5500',
        error: '#ffb4ab',
        'surface-container-low': '#1c1b1b',
        'on-surface-variant': '#bac9cc',
        'surface-variant': '#353534',
        'on-surface': '#e5e2e1',
        'on-error': '#690005',
        'surface-tint': '#00daf3',
        'error-container': '#93000a',
        'on-secondary': '#053900',
        'tertiary-container': '#fec931',
        'panel': '#121212',
        'panel-border': '#262626',
        'row-hover': '#1A1A1A',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        unit: '4px',
        'margin-mobile': '16px',
        'container-max': '1200px',
        'margin-desktop': '48px',
        xs: '8px',
        sm: '16px',
        base: '4px',
        lg: '40px',
        md: '24px',
        xl: '64px',
      },
      fontFamily: {
        display: ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Geist', 'monospace'],
        code: ['Geist', 'monospace'],
        'code-sm': ['Geist', 'monospace'],
        'label-caps': ['Geist', 'monospace'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        code: ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'code-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 8px rgba(0, 229, 255, 0.3)' },
          '50%': { boxShadow: '0 0 16px rgba(0, 229, 255, 0.6)' },
        },
        'flow-anim': {
          '0%': { backgroundPosition: '100% 0' },
          '100%': { backgroundPosition: '-100% 0' },
        },
        'float-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'pulse-glow': 'pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'flow-anim': 'flow-anim 2s linear infinite',
        'float-up': 'float-up 0.6s ease-out forwards',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
